# Default values for get.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 074368059797.dkr.ecr.eu-central-1.amazonaws.com/nikitasadok
  tag: stable
  pullPolicy: Always
  HOST_PORT: "8081"
  ENDPOINT: "back-srv:8083"

service:
  type: ClusterIP
  port: 8081

ingress:
  enabled: false
  annotations: {}

nodeSelector: {}

tolerations: []

affinity: {}
